scraper:
  regions:
    - name: "barreiro"
      url: "https://www.olx.com.br/imoveis/venda/apartamentos/estado-mg/belo-horizonte-e-regiao/barreiro?sf=1"
    - name: "pampulha"
      url: "https://www.olx.com.br/imoveis/venda/apartamentos/estado-mg/belo-horizonte-e-regiao/pampulha?sf=1"
    - name: "venda_nova"
      url: "https://www.olx.com.br/imoveis/venda/apartamentos/estado-mg/belo-horizonte-e-regiao/venda-nova?sf=1"
    - name: "zona_centro_sul"
      url: "https://www.olx.com.br/imoveis/venda/apartamentos/estado-mg/belo-horizonte-e-regiao/zona-centro-sul?sf=1"
    - name: "zona_leste"
      url: "https://www.olx.com.br/imoveis/venda/apartamentos/estado-mg/belo-horizonte-e-regiao/zona-leste?sf=1"
    - name: "zona_nordeste"
      url: "https://www.olx.com.br/imoveis/venda/apartamentos/estado-mg/belo-horizonte-e-regiao/zona-nordeste?sf=1"
    - name: "zona_noroeste"
      url: "https://www.olx.com.br/imoveis/venda/apartamentos/estado-mg/belo-horizonte-e-regiao/zona-noroeste?sf=1"
    - name: "zona_norte"
      url: "https://www.olx.com.br/imoveis/venda/apartamentos/estado-mg/belo-horizonte-e-regiao/zona-norte?sf=1"
    - name: "zona_oeste"
      url: "https://www.olx.com.br/imoveis/venda/apartamentos/estado-mg/belo-horizonte-e-regiao/zona-oeste?sf=1"
  csv_filename: "data/new_links_olx.csv"
  sleep_time: 3
  links_filename: "new_links_olx.csv"
  detailed_filename: "dados_detalhados_olx.csv"

model:
  best_params:
    - 142
    - 18
    - 3
    - 2
  avg_price_per_sqmt_dict:
    zona_norte: 8.394846992222611
    zona_centro_sul: 9.09851811665617
    barreiro: 8.503898358767296
    venda_nova: 8.36755862148199
    zona_oeste: 8.843083032977592
    zona_noroeste: 7.96617976451086
    zona_leste: 8.816877975750044
    pampulha: 8.626722968908846
    zona_nordeste: 8.66487771346997

  features:
    - "ROOMS_NO"
    - "BATH_NO"
    - "PARKING_SPOTS"
    - "DETAIL_Academia"
    - "DETAIL_Ar condicionado"
    - "DETAIL_Armários na cozinha"
    - "DETAIL_Armários no quarto"
    - "DETAIL_Churrasqueira"
    - "DETAIL_Mobiliado"
    - "DETAIL_Piscina"
    - "DETAIL_Varanda"
    - "DETAIL_Área de serviço"
    - "REGION_barreiro"
    - "REGION_pampulha"
    - "REGION_venda_nova"
    - "REGION_zona_leste"
    - "REGION_zona_nordeste"
    - "REGION_zona_noroeste"
    - "REGION_zona_norte"
    - "REGION_zona_oeste"
    - "LOG_AREA"
    - "LOG_AVG_PRICE_PER_SQMT_BY_REGION"
    - "UTILS"
  target:
    - "LOG_PRICE"
    
score_new_pred:
  features:
    - ROOMS_NO
    - BATH_NO
    - PARKING_SPOTS
    - DETAIL_Academia
    - DETAIL_Ar condicionado
    - DETAIL_Armários na cozinha
    - DETAIL_Armários no quarto
    - DETAIL_Churrasqueira
    - DETAIL_Mobiliado
    - DETAIL_Piscina
    - DETAIL_Varanda
    - DETAIL_Área de serviço
    - REGION_barreiro
    - REGION_pampulha
    - REGION_venda_nova
    - REGION_centro_sul
    - REGION_zona_leste
    - REGION_zona_nordeste
    - REGION_zona_noroeste
    - REGION_zona_norte
    - REGION_zona_oeste
    - LOG_AREA
    - LOG_AVG_PRICE_PER_SQMT_BY_REGION
    - UTILS
  target:
    - LOG_PRICE