scraper:
  regions:
    - name: "barreiro"
      url: "https://www.olx.com.br/imoveis/venda/apartamentos/estado-mg/belo-horizonte-e-regiao/barreiro?sf=1"
    - name: "pampulha"
      url: "https://www.olx.com.br/imoveis/venda/apartamentos/estado-mg/belo-horizonte-e-regiao/pampulha?sf=1"
    - name: "venda nova"
      url: "https://www.olx.com.br/imoveis/venda/apartamentos/estado-mg/belo-horizonte-e-regiao/venda-nova?sf=1"
    - name: "centro sul"
      url: "https://www.olx.com.br/imoveis/venda/apartamentos/estado-mg/belo-horizonte-e-regiao/zona-centro-sul?sf=1"
    - name: "zona leste"
      url: "https://www.olx.com.br/imoveis/venda/apartamentos/estado-mg/belo-horizonte-e-regiao/zona-leste?sf=1"
    - name: "zona nordeste"
      url: "https://www.olx.com.br/imoveis/venda/apartamentos/estado-mg/belo-horizonte-e-regiao/zona-nordeste?sf=1"
    - name: "zona noroeste"
      url: "https://www.olx.com.br/imoveis/venda/apartamentos/estado-mg/belo-horizonte-e-regiao/zona-noroeste?sf=1"
    - name: "zona norte"
      url: "https://www.olx.com.br/imoveis/venda/apartamentos/estado-mg/belo-horizonte-e-regiao/zona-norte?sf=1"
    - name: "zona oeste"
      url: "https://www.olx.com.br/imoveis/venda/apartamentos/estado-mg/belo-horizonte-e-regiao/zona-oeste?sf=1"
  csv_filename: "data/new_links_olx.csv"
  sleep_time: 3
  links_filename: "new_links_olx.csv"
  detailed_filename: "dados_detalhados_olx.csv"
