name: Daily Run Workflow

on:
  schedule:
    - cron: '15 14 * * *' # This runs the job every day at 2 PM UTC
  workflow_dispatch: # <- This line allows for manual triggering

permissions:
  id-token: write
  contents: read

jobs:
  daily_run:
    name: Run Daily Tasks
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ./src  # Add PYTHONPATH environment variable
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Debug Step: Show current directory
      - name: Show current directory
        run: pwd

      # Debug Step: List directory structure
      - name: List directory structure
        run: ls -R

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Install Dependencies
      - name: Install Dependencies
        run: pip install --no-cache-dir -r requirements.txt

      # Run link_scraper.py
      - name: Execute link_scraper.py
        run: python src/scraping/link_scraper.py

      # Run element_fetch.py
      - name: Execute element_fetch.py
        run: python src/scraping/element_fetch.py

      # Run score_new_predictions.py
      - name: Execute score_new_predictions.py
        run: python src/transformation/score_new_predictions.py
